### ISSUE TITLE
does not do anything even though it is enabled

### ISSUE THREAD

**Issue by hotheadb1** [aDerpling/KillForHealth#2]
No matter what what number i set the healing to it doesn't heal/set max health me and it is enabled.

**Comment by DerplingDev** [comment]
You must wear the accessory added by the mod, and multiplayer doesn't work at the moment.

**Comment by hotheadb1** [comment]
sorry for the delayed response but how do i get that accessory because i cant find a answer on google

**Comment by DerplingDev** [comment]
You can get it from Hero's Mod or Cheat Sheet, it is called "The Ring of Endless Blood"
